### ISSUE TITLE
Site no longer works

### ISSUE THREAD

**Issue by ToRRent1812** [drecken/twitchsubscribers.com#10]
last month, everything was fine, today I'm trying to log in and nothing.

**Comment by Shadewarp** [comment]
Same issue still

**Comment by drecken** [comment]
Twitch secret expired. Fixed now.

**Comment by JosephRedfern** [comment]
@drecken Should the site still be working? I am trying to help someone to export a list of their subs so can't test this myself.

**Comment by drecken** [comment]
> @drecken Should the site still be working? I am trying to help someone to export a list of their subs so can't test this myself.

It should be working. Don't think there is an export option tho
