### ISSUE TITLE
500 Response after "Show Me My Twitch" (Again)

### ISSUE THREAD

**Issue by levinsonalex** [drecken/twitchsubscribers.com#11]
Reopening, issue has begun again. Doesn't seem related to twitch service callback anymore, though it is 301 -> 302 -> 500 right now.

_Originally posted by @levinsonalex in https://github.com/drecken/twitchsubscribers.com/issues/6#issuecomment-703961432_

**Comment by drecken** [comment]
Looks like twitch changed something in their API. Should be good now
