### ISSUE TITLE
Ability to differentiate Twitch Prime subs and one-time gifted subs with recurring subs

### ISSUE THREAD

**Issue by eliasthompson** [drecken/twitchsubscribers.com#2]
This is a great tool, but it would be nice to know which subs I can count on long term, and which subs are only here for the month. Some way to filter between or at the very least note Twitch Prime subs, one-time gifted subs, and regular recurring subs would be handy.

**Comment by jakebathman** [comment]
I've added visibility into Prime subs in #3, but the Twitch API is currently returning Prime subs as Tier 1 in the `/subscriptions` endpoint. So, this tool will show them soon, but not until Twitch fixes that part of the API. 🤞

**Comment by drecken** [comment]
#3 is now merged and Prime Subs should show up correctly. 👍 to @jakebathman
