### ISSUE TITLE
500 Response After "Show Me My Twitch"

### ISSUE THREAD

**Issue by levinsonalex** [drecken/twitchsubscribers.com#6]
https://www.twitchsubscribers.com/twitch/callback endpoint returns a 500 error, and displays "Whoops, looks like something went wrong."

**Comment by MeganRovi** [comment]
I'm having the same issue

**Comment by drecken** [comment]
Should be fixed now

**Comment by levinsonalex** [comment]
Reopening, issue has begun again. Doesn't seem related to twitch service callback anymore, though it is 301 -> 302 -> 500 right now.
